- name: Install glusterfs
  apt:
    name: glusterfs-server
    state: present
  notify: glusterfs-started

- meta: flush_handlers

- name: Create bricks directory
  file:
    dest: "{{ glusterfs_brick_dir }}"
    mode: "0755"
    owner: "root"
    group: "root"
    state: directory

- name: Create volumes
  gluster_volume:
    state: present
    name: "{{ item }}"
    bricks: "{{ glusterfs_brick_dir }}/{{ item }}"
    cluster: "{{ groups.glusterfs }}"
    force: true
    replicas: "{{ groups.glusterfs | count }}"
  run_once: true
  with_items: "{{ glusterfs_volumes }}"

- name: Ensure volumes are started
  gluster_volume:
    state: started
    name: "{{ item }}"
  with_items: "{{ glusterfs_volumes }}"
